version: '3.8'

services:
  frontend:
    image: stock_view_frontend
    build:
      context: ~/projects/stock_view_frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    image: stock_view_backend
    build:
      context: ~/projects/stock_view_backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: stock_view
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
